apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Chart.Name }}-migrate-{{ .Release.Revision }}"
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.selectorLabels | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- toYaml .Values.selectorLabels | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["sh", "-c"]
          args:
            - |
              apk add --no-cache postgresql-client &&
              for f in /app/migrations/*.up.sql; do
                echo "Applying migration: $f"
                psql "$DB_URL" -f "$f"
              done
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: db_url
      serviceAccountName: {{ .Values.serviceAccountName }}
