{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}"
  namespace: "{{ .Values.namespace }}"
type: "{{ .Values.secrets.type }}"
data:
  {{- toYaml .Values.secrets.data | nindent 2 }}
{{- end }}
